### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by rbharath** [dfinity/dhc#1]
If we're interested in playing with dhc, what would be the easiest way to build the library? How can we run the test suite?

**Comment by blynn** [comment]
I just added our "Hero Engine" to the repo, which is an incomplete and slow wasm interpreter that we use internally for testing. (I had intended to migrate to e.g. https://github.com/SPY/haskell-wasm to avoid making Hero public, but it could be a while before we get around to it.)

Building with nix should work now. Please reopen if it doesn't.
